#ifndef PROTOCOL_H
#define PROTOCOL_H

enum ENUM_MSG_TYPE{
    ENUM_MSG_TYPE_MIN=0,
    ENUM_MSG_TYPE_REGISTR_REQUSET,
    ENUM_MSG_TYPE_REGISTR_RESPOND,
    ENUM_MSG_TYPE_LOGIN_REQUSET,
    ENUM_MSG_TYPE_LOGIN_RESPOND,
    ENUM_MSG_TYPE_FIND_USER_REQUSET,
    ENUM_MSG_TYPE_FIND_USER_RESPOND,
    ENUM_MSG_TYPE_ONLINE_USER_REQUSET,
    ENUM_MSG_TYPE_ONLINE_USER_RESPOND,
    ENUM_MSG_TYPE_ADD_FRIEND_REQUSET,
    ENUM_MSG_TYPE_ADD_FRIEND_RESPOND,
    ENUM_MSG_TYPE_ADD_FRIEND_AGREE_REQUSET,
    ENUM_MSG_TYPE_ADD_FRIEND_AGREE_RESPOND,
    ENUM_MSG_TYPE_FLUSH_FRIEND_REQUSET,
    ENUM_MSG_TYPE_FLUSH_FRIEND_RESPOND,
    ENUM_MSG_TYPE_DELETE_FRIEND_REQUSET,
    ENUM_MSG_TYPE_DELETE_FRIEND_RESPOND,
    ENUM_MSG_TYPE_CHAT_REQUSET,
    ENUM_MSG_TYPE_CHAT_RESPOND,
    ENUM_MSG_TYPE_MKDIR_REQUEST,
    ENUM_MSG_TYPE_MKDIR_RESPOND,
    ENUM_MSG_TYPE_FLUSH_FILE_REQUSET,
    ENUM_MSG_TYPE_FLUSH_FILE_RESPOND,
    ENUM_MSG_TYPE_DEL_DIR_REQUSET,
    ENUM_MSG_TYPE_DEL_DIR_RESPOND,
    ENUM_MSG_TYPE_DEL_FILE_REQUSET,
    ENUM_MSG_TYPE_DEL_FILE_RESPOND,
    ENUM_MSG_TYPE_RENAME_FILE_REQUSET,
    ENUM_MSG_TYPE_RENAME_FILE_RESPOND,
    ENUM_MSG_TYPE_MV_FILE_REQUSET,
    ENUM_MSG_TYPE_MV_FILE_RESPOND,
    ENUM_MSG_TYPE_SHARE_FILE_REQUSET,
    ENUM_MSG_TYPE_SHARE_FILE_RESPOND,
    ENUM_MSG_TYPE_SHARE_FILE_AGREE_REQUSET,
    ENUM_MSG_TYPE_SHARE_FILE_AGREE_RESPOND,
    ENUM_MSG_TYPE_UPLOAD_FILE_INIT_REQUSET,
    ENUM_MSG_TYPE_UPLOAD_FILE_INIT_RESPOND,
    ENUM_MSG_TYPE_UPLOAD_FILE_DATA_REQUSET,
    ENUM_MSG_TYPE_UPLOAD_FILE_DATA_RESPOND,
    ENUM_MSG_TYPE_MAX=0x00ffffff
};
typedef unsigned int uint;
struct PDU{
    uint uiPDULen;      //协议总长度
    uint uiMsgLen;      //柔性数组长度
    uint uiMsgType;     //消息类型
    char caData[64];    //参数
    char caMsg[];       //实际消息
};

struct FileInfo{
    char caName[32];
    int iFileType;
};

PDU* mkPDU(uint uiMsgType,uint uiMsgLen=0);
#endif // PROTOCOL_H
